---
title: "assignment04<eb1238>"
author: "Elena Bagnera"
date: "10/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(ggrepel)
library(scales)
```

## Fiscal decentralization across countries

```{r loading imfdata}
imf_fd <- read_dta('Data/Fiscal Decentralization STATA File - 2020 GFS Database Vintage.dta') 

```

```{r imfcleaning_graph1}

countries <- c("United States", "Canada", "New Zealand", "Australia")

imf_fd_graph1 <- imf_fd %>%
  filter(year==2019) %>%
  select(country, sd_sng, rd_sng) %>%
  filter(country %in% countries) %>%
  pivot_longer(
cols = c(sd_sng, rd_sng),
names_to = "FD_type",
values_to = "value"
  )
```

```{r imfgraph1}

imf_fd_graph1 %>% 
  ggplot() +
  geom_col(mapping = aes(x = country, y = value, fill=FD_type), position="dodge")+
  theme_classic() + 
  xlab("Countries") + 
  ylab("% decentralized spending and revenue") +
  labs(caption="https://data.imf.org/?sk=1C28EBFB-62B3-4B0C-AED3-048EEEBB684F") +
  labs(title = "Spending is more decentralized than tax revenue in former colonies of the British Empire", subtitle="IMF fiscal Decentralization Database, 2019") +
 scale_fill_discrete(name = "Decentralization type", labels = c("Revenue decentralization", "Spending decentralization")) +
  theme(plot.caption = element_text(hjust = 0, face= "italic"), 
        plot.title.position = "plot", 
        plot.caption.position =  "plot") +
   scale_y_continuous(labels = scales::percent)

```

## Decentralization trends in Spain over time

```{r imfcleaning_graph2}
imf_fd_graph2 <- imf_fd %>%
  filter(country=="Spain") %>%
  filter(year>=1980) %>%
  select(country, year, sd_sng, rd_sng, taxd_sng) %>%
  rename("Spending"=sd_sng, "Tax revenue"=taxd_sng, "Total revenue"=rd_sng) %>%
  pivot_longer(
cols = c("Spending", "Total revenue", "Tax revenue"),
names_to = "FD_type",
values_to = "value"
  ) 

```

```{r imf_graph2}

labels <- c("Decentralized tax revenue", "Decentralized revenue", "Decentralized spending")
library(directlabels)

imf_fd_graph2 %>% 
ggplot() +
geom_line(mapping = aes(x = year, y = value, color=FD_type), size=1, alpha= 0.8) +
  geom_point(mapping = aes(x = year, y = value), size=0.7, color="dark blue") + 
  geom_dl(aes(x=year, y=value, label=FD_type, color=FD_type), method = list(dl.trans(x = x + .3), "last.bumpup")) +
  theme_classic() + 
  xlab("Years") + 
  ylab("% of decentralization") +
  labs(caption="https://data.imf.org/?sk=1C28EBFB-62B3-4B0C-AED3-048EEEBB684F") +
  labs(title = "Spain has undergone radical decentralization reforms", subtitle="IMF Fiscal Decentralization databse, 1980-2019", fill="") +
  theme(plot.caption = element_text(hjust = 0, face= "italic"), 
        plot.title.position = "plot", 
        plot.caption.position =  "plot")  +
  scale_y_continuous(labels = scales::percent_format(accuracy=1), limits=c(0, 0.5)) +
  coord_cartesian(clip = 'off') +
  theme(legend.position = 'none',
  plot.margin = margin(0.1, 2.6, 0.1, 0.1, "cm"))

```


## % of renewabe energy & population

```{r owid_data}
owid_energy <- read_csv('https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv') 
```

```{r owid_cleaning}

owid_energy_graph1 <- owid_energy %>%
  filter(
    year==2019, 
    !is.na(renewables_share_energy),
    !country %in% regions) %>%
  select(country, year, population, renewables_share_energy) 

regions <- c("North America", "Europe", "Asia Pacific", "Africa", "South & Central America", "Other South America", "Other North America", "Other Asia & Pacific", "Europe (other)", "Other Southern Africa", "Other Northern Africa", "Other South America", "Other Southern Africa", "World")

highlights <- owid_energy_graph1 %>%
  filter(country=="China"| country=="India"| country=="United States" | country=="Russia"| country=="Brazil"| country=="Pakistan"| country=="Bangladesh" | country=="Indonesia")


```


```{r owid_graph1}
owid_energy_graph1 %>%
    ggplot() +
  geom_point(mapping = aes(x = population, y = renewables_share_energy), size=1.5, color="dark green") +
  geom_label_repel(data=highlights, aes(x=population, y=renewables_share_energy, label=country), size=3, box.padding = 0.5, max.overlaps=Inf) + 
  theme_classic() + 
  xlab("Population") + 
  ylab("% of renewables in energy mix") +
  labs(caption="The data comes from the Our World In Data environmental database:\nhttps://ourworldindata.org/renewable-energy") +
  labs(title = "The most populous countries tend to have a low renewable levels in energy mix", subtitle="Our World in Data (2019)", fill="") +
  theme(plot.caption = element_text(hjust = 0, face= "italic"), 
        plot.title.position = "plot", 
        plot.caption.position =  "plot")+
  scale_x_log10(labels=scales::comma)

```

## Types of renewable energy

```{r owid_cleaning2}
main_econ <-c("Japan", "United States", "China", "India", "Germany", "United Kingdom")

owid_energy_graph2 <- owid_energy %>%
  filter(year==2019, country %in% main_econ) %>%
  select(country, wind_share_energy, solar_share_energy, hydro_share_energy, biofuel_share_energy, other_renewables_share_energy) %>%
  pivot_longer(
cols = c(wind_share_energy, solar_share_energy, hydro_share_energy, biofuel_share_energy, other_renewables_share_energy),
names_to = "renewable_type",
values_to = "value"
  ) 

```
    
    ```{r owid_graph4}

   owid_energy_graph2 %>%
      ggplot() +
      geom_col(mapping = aes(x = country, y = value, fill=renewable_type), position="dodge") +
        theme_classic() + 
        xlab("Countries") + 
        ylab("% of energy type in energy mix") +
        labs(caption="The data comes from the Our World In Data environmental database:\nhttps://ourworldindata.org/renewable-energy") +
        labs(title = "Wind and hydroelectric energy are the main renewables in largest economies", subtitle="Our World in Data, 2019") +
      coord_flip() +
  theme(plot.caption = element_text(hjust = 0, face= "italic"), 
        plot.title.position = "plot", 
        plot.caption.position =  "plot") +
      scale_fill_discrete(name = "Type of renewable", labels = c("Biofuel", "Hydroelectric", "Other", "Solar", "Wind")) +
      scale_y_continuous()

      # remove x label, add percentages to bars
    ```
    
  
    
    
